//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CDRMEntities : DbContext
    {
        public CDRMEntities()
            : base("name=CDRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COD_ADJUSTLEVEL> COD_ADJUSTLEVEL { get; set; }
        public virtual DbSet<COD_ADJUSTUSER> COD_ADJUSTUSER { get; set; }
        public virtual DbSet<COD_CCASUSER> COD_CCASUSER { get; set; }
        public virtual DbSet<COD_RG_PARA> COD_RG_PARA { get; set; }
        public virtual DbSet<COD_RG_REASON> COD_RG_REASON { get; set; }
        public virtual DbSet<COD_RG_REJECT> COD_RG_REJECT { get; set; }
        public virtual DbSet<LOG_PROGRESS> LOG_PROGRESS { get; set; }
        public virtual DbSet<LOG_RG_ILRC> LOG_RG_ILRC { get; set; }
        public virtual DbSet<PORTAL_AUTHORITY> PORTAL_AUTHORITY { get; set; }
        public virtual DbSet<PORTAL_FUNCTION> PORTAL_FUNCTION { get; set; }
        public virtual DbSet<PORTAL_GROUP> PORTAL_GROUP { get; set; }
        public virtual DbSet<PORTAL_ICRS_USER> PORTAL_ICRS_USER { get; set; }
        public virtual DbSet<PORTAL_USER> PORTAL_USER { get; set; }
        public virtual DbSet<PORTAL_USER_GROUP> PORTAL_USER_GROUP { get; set; }
        public virtual DbSet<RG_ADJUST> RG_ADJUST { get; set; }
        public virtual DbSet<RG_PADJUST> RG_PADJUST { get; set; }
        public virtual DbSet<RG_PADJUST_TMP> RG_PADJUST_TMP { get; set; }
        public virtual DbSet<RG_PARA_D_CHECK> RG_PARA_D_CHECK { get; set; }
        public virtual DbSet<RG_PARA_D_FINAL> RG_PARA_D_FINAL { get; set; }
        public virtual DbSet<RG_PARA_D_INIT> RG_PARA_D_INIT { get; set; }
        public virtual DbSet<RG_PARA_M_ACTIVE> RG_PARA_M_ACTIVE { get; set; }
        public virtual DbSet<RG_PARA_M_CHECK> RG_PARA_M_CHECK { get; set; }
        public virtual DbSet<RG_PARA_M_FINAL> RG_PARA_M_FINAL { get; set; }
        public virtual DbSet<RG_PARA_M_INIT> RG_PARA_M_INIT { get; set; }
    
        public virtual int SP_ELGB_PAD01(string vID, string userID, string userName, ObjectParameter jCIC_DATE, ObjectParameter resp_code)
        {
            var vIDParameter = vID != null ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELGB_PAD01", vIDParameter, userIDParameter, userNameParameter, jCIC_DATE, resp_code);
        }
    
        public virtual int SP_ELGB_PAD02(string vID, string jCIC_DATE, string rEASON, ObjectParameter eSTIMATE_RESULT, ObjectParameter rEJECTREASON, ObjectParameter pRJ_RESULT, ObjectParameter pRJ_REJECTREASON, ObjectParameter resp_code)
        {
            var vIDParameter = vID != null ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(string));
    
            var jCIC_DATEParameter = jCIC_DATE != null ?
                new ObjectParameter("JCIC_DATE", jCIC_DATE) :
                new ObjectParameter("JCIC_DATE", typeof(string));
    
            var rEASONParameter = rEASON != null ?
                new ObjectParameter("REASON", rEASON) :
                new ObjectParameter("REASON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELGB_PAD02", vIDParameter, jCIC_DATEParameter, rEASONParameter, eSTIMATE_RESULT, rEJECTREASON, pRJ_RESULT, pRJ_REJECTREASON, resp_code);
        }
    
        public virtual int SP_ELGB_PAD03(string vID, ObjectParameter rEJECTREASON, ObjectParameter resp_code)
        {
            var vIDParameter = vID != null ?
                new ObjectParameter("vID", vID) :
                new ObjectParameter("vID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELGB_PAD03", vIDParameter, rEJECTREASON, resp_code);
        }
    }
}
