//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMPNEntities : DbContext
    {
        public CMPNEntities()
            : base("name=CMPNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMPN> CMPN { get; set; }
        public virtual DbSet<CMPN_AVY_CNL_EXBOOK> CMPN_AVY_CNL_EXBOOK { get; set; }
        public virtual DbSet<CMPN_RLT_NM_LST> CMPN_RLT_NM_LST { get; set; }
    }
}
