//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMPN
    {
        public string CMPN_ID { get; set; }
        public string CMPN_NM { get; set; }
        public string CMPN_DSC { get; set; }
        public Nullable<decimal> CMPN_TP_ID { get; set; }
        public Nullable<decimal> INL_OU_ID { get; set; }
        public string INL_EMPE_NO { get; set; }
        public string CMPN_PROM_PRD_ID { get; set; }
        public Nullable<decimal> CMPN_FILTER_TYPID { get; set; }
        public string CMPN_EXPC_STRT_DT { get; set; }
        public string CMPN_EXPC_END_DT { get; set; }
        public string CMPN_EXPC_CLOSE_DT { get; set; }
        public string CMPN_DETAIL_DSC { get; set; }
        public Nullable<decimal> CMPN_EXPC_CNL_ID { get; set; }
        public Nullable<decimal> CMPN_FRQ_TP_ID { get; set; }
        public string CMPN_BASE_DSC { get; set; }
        public Nullable<decimal> CMPN_APPROVE_STS { get; set; }
        public string CMPN_ASSIGN_MIS { get; set; }
        public string CREATED_DT { get; set; }
        public Nullable<System.DateTime> LST_MTN_DT { get; set; }
        public string CRSS_FLG { get; set; }
    }
}
