//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMPN_RLT_NM_LST
    {
        public string CMPN_ID { get; set; }
        public decimal CMPN_SEQ { get; set; }
        public decimal CMPN_AVY_ID { get; set; }
        public decimal CMPN_CELL_ID { get; set; }
        public decimal CMPN_CNL_ID { get; set; }
        public decimal CMPN_OFFER_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string UPDT_DT { get; set; }
        public string UPDT_USER { get; set; }
        public string VLD_FLG { get; set; }
        public string VLD_USER { get; set; }
        public string VLD_MEMO { get; set; }
        public Nullable<System.DateTime> MTN_DT { get; set; }
        public Nullable<decimal> NAMING_LST_SEQ { get; set; }
    }
}
