//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMPN_AVY_CNL_EXBOOK
    {
        public string CMPN_ID { get; set; }
        public decimal CMPN_SEQ { get; set; }
        public Nullable<decimal> CMPN_AVY_ID { get; set; }
        public Nullable<decimal> CMPN_CNL_ID { get; set; }
        public Nullable<decimal> CMPN_CELL_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string CMPN_ACT_STRT_DT { get; set; }
        public string CMPN_ACT_END_DT { get; set; }
        public string COL_1 { get; set; }
        public string COL_2 { get; set; }
        public string COL_3 { get; set; }
        public string COL_4 { get; set; }
        public string COL_5 { get; set; }
        public string COL_6 { get; set; }
        public string COL_7 { get; set; }
        public string COL_8 { get; set; }
        public string COL_9 { get; set; }
        public string COL_10 { get; set; }
        public string COL_11 { get; set; }
        public string COL_12 { get; set; }
        public string COL_13 { get; set; }
        public string COL_14 { get; set; }
        public string COL_15 { get; set; }
        public string COL_16 { get; set; }
        public string COL_17 { get; set; }
        public string COL_18 { get; set; }
        public string COL_19 { get; set; }
        public string COL_20 { get; set; }
        public string UPDT_DT { get; set; }
        public string UPL_FILE_NM { get; set; }
        public string MTN_DT { get; set; }
    }
}
