//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_RG_ILRC
    {
        public string CMPN_ID { get; set; }
        public string CMPN_EXPC_STRT_DT { get; set; }
        public string CMPN_EXPC_END_DT { get; set; }
        public Nullable<decimal> CNT { get; set; }
        public string IMPORT_USERID { get; set; }
        public string IMPORT_USERNAME { get; set; }
        public string IMPORT_DT { get; set; }
    }
}
