//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_VIP
    {
        public string CST_ID { get; set; }
        public string YYYYMM { get; set; }
        public string UPD_DT { get; set; }
        public Nullable<decimal> ELG_VIP_TP_ID { get; set; }
        public string ELG_VIP_TP_EFF_DT { get; set; }
        public Nullable<decimal> VIP_TP_ID { get; set; }
        public string VIP_TP_EFF_DT { get; set; }
        public Nullable<decimal> VIP_BAL_AMT { get; set; }
        public Nullable<decimal> DEP_AVG_BAL_AMT { get; set; }
        public Nullable<decimal> NT_INVSM_BAL_INCLD_PREPAID { get; set; }
        public Nullable<decimal> NT_CMLV_PREM_AMT { get; set; }
        public Nullable<decimal> AUM { get; set; }
        public Nullable<decimal> LST_1YR_CRD_SPND_TOT_AMT { get; set; }
        public Nullable<decimal> MRTG_BAL { get; set; }
        public Nullable<decimal> FRX_EXG_MRG_TRD { get; set; }
        public Nullable<decimal> CB_NMNL_PRNCPL { get; set; }
        public Nullable<decimal> FEIS_SUB_BRKRG { get; set; }
        public Nullable<decimal> CRD_VIP_TOB_FLG { get; set; }
        public Nullable<decimal> HW_FLG { get; set; }
        public Nullable<decimal> CRP_FLG { get; set; }
    }
}
