//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RG_ADJUST
    {
        public string ID { get; set; }
        public string APPLY_DATE { get; set; }
        public string APPLY_TIME { get; set; }
        public string ACCT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> TOT_LIMIT { get; set; }
        public Nullable<decimal> APPLY_AMT { get; set; }
        public string USESITE { get; set; }
        public string PLACE { get; set; }
        public string ADJUST_DATE_S { get; set; }
        public string ADJUST_DATE_E { get; set; }
        public string REASON1 { get; set; }
        public string REASON2 { get; set; }
        public string REASON3 { get; set; }
        public string REASON { get; set; }
        public string REMARK { get; set; }
        public string FAC_AUTH { get; set; }
        public Nullable<decimal> APPROVE_AMT_MAX { get; set; }
        public Nullable<decimal> USABILITY_AMT { get; set; }
        public Nullable<decimal> OVERPAY_AMT_PRO { get; set; }
        public Nullable<decimal> APPROVE_AMT { get; set; }
        public Nullable<decimal> OVERPAY_AMT { get; set; }
        public string ESTIMATE_RESULT { get; set; }
        public string REJECTREASON { get; set; }
        public string APPROVE_RESULT { get; set; }
        public string CHIEF_FLAG { get; set; }
        public string CHIEF_REMARK { get; set; }
        public string PENDING_FLAG { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string CHIEF_ID { get; set; }
        public string CHIEF_NAME { get; set; }
        public string JCIC_DATE { get; set; }
        public string TYPE { get; set; }
        public string CCAS_CODE { get; set; }
        public string CCAS_STATUS { get; set; }
        public string CCAS_DT { get; set; }
        public string PROC_DATE { get; set; }
        public string PROC_TIME { get; set; }
        public string ICARE_YN { get; set; }
        public string PRJ_YN { get; set; }
        public string PRJ_RESULT { get; set; }
        public string PRJ_REJECTREASON { get; set; }
        public Nullable<decimal> CREDIT_AMT { get; set; }
    }
}
