//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RG_ID
    {
        public string ACCT_ID { get; set; }
        public string CHI_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string RISK_LEVEL { get; set; }
        public string CA_REVOLVE_LEVEL { get; set; }
        public Nullable<decimal> TOT_LIMIT { get; set; }
        public string ACNO_STATUS { get; set; }
        public Nullable<System.DateTime> CA_FIRST_CARD_ISSU_DATE { get; set; }
        public Nullable<decimal> LV_CARD_COUNT { get; set; }
        public string STATUS { get; set; }
        public string VOCATION { get; set; }
        public string BILL_ADDR { get; set; }
        public string TEL_OFFICE { get; set; }
        public string TEL_HOME { get; set; }
        public string MOBIL_TEL { get; set; }
        public string LATEST_1_MNTH { get; set; }
        public string LATEST_2_MNTH { get; set; }
        public string LATEST_3_MNTH { get; set; }
        public string LATEST_4_MNTH { get; set; }
        public string LATEST_5_MNTH { get; set; }
        public string LATEST_6_MNTH { get; set; }
        public string LATEST_7_MNTH { get; set; }
        public string LATEST_8_MNTH { get; set; }
        public string LATEST_9_MNTH { get; set; }
        public string LATEST_10_MNTH { get; set; }
        public string LATEST_11_MNTH { get; set; }
        public string LATEST_12_MNTH { get; set; }
        public Nullable<decimal> CONSUME_1 { get; set; }
        public Nullable<decimal> CONSUME_2 { get; set; }
        public Nullable<decimal> CONSUME_3 { get; set; }
        public Nullable<decimal> CONSUME_4 { get; set; }
        public Nullable<decimal> CONSUME_5 { get; set; }
        public Nullable<decimal> CONSUME_6 { get; set; }
        public Nullable<decimal> CONSUME_7 { get; set; }
        public Nullable<decimal> CONSUME_8 { get; set; }
        public Nullable<decimal> CONSUME_9 { get; set; }
        public Nullable<decimal> CONSUME_10 { get; set; }
        public Nullable<decimal> CONSUME_11 { get; set; }
        public Nullable<decimal> CONSUME_12 { get; set; }
        public Nullable<decimal> PRECASH_1 { get; set; }
        public Nullable<decimal> PRECASH_2 { get; set; }
        public Nullable<decimal> PRECASH_3 { get; set; }
        public Nullable<decimal> PRECASH_4 { get; set; }
        public Nullable<decimal> PRECASH_5 { get; set; }
        public Nullable<decimal> PRECASH_6 { get; set; }
        public Nullable<decimal> PRECASH_7 { get; set; }
        public Nullable<decimal> PRECASH_8 { get; set; }
        public Nullable<decimal> PRECASH_9 { get; set; }
        public Nullable<decimal> PRECASH_10 { get; set; }
        public Nullable<decimal> PRECASH_11 { get; set; }
        public Nullable<decimal> PRECASH_12 { get; set; }
        public string UN_PAYMENT_RATE_1 { get; set; }
        public string UN_PAYMENT_RATE_2 { get; set; }
        public string UN_PAYMENT_RATE_3 { get; set; }
        public string UN_PAYMENT_RATE_4 { get; set; }
        public string UN_PAYMENT_RATE_5 { get; set; }
        public string UN_PAYMENT_RATE_6 { get; set; }
        public string UN_PAYMENT_RATE_7 { get; set; }
        public string UN_PAYMENT_RATE_8 { get; set; }
        public string UN_PAYMENT_RATE_9 { get; set; }
        public string UN_PAYMENT_RATE_10 { get; set; }
        public string UN_PAYMENT_RATE_11 { get; set; }
        public string UN_PAYMENT_RATE_12 { get; set; }
        public string STMT_CYCLE_DESC { get; set; }
        public string PAY_DEADLINE { get; set; }
        public Nullable<decimal> ACCT_TOT_BILL { get; set; }
        public Nullable<decimal> ACCT_MIN_PAY { get; set; }
        public Nullable<decimal> CA_LAST_PAY_AMT { get; set; }
        public Nullable<System.DateTime> CA_LAST_PAY_DATE { get; set; }
        public Nullable<decimal> ACNO_FEIBDM_AMT { get; set; }
        public Nullable<decimal> C_CA_TOT_UNPAID_AMT { get; set; }
        public Nullable<decimal> C_CA_TOT_AMT_CONSUME { get; set; }
        public string ADJ_REASON { get; set; }
        public string ADJ_AREA { get; set; }
        public string ADJ_EFF_START_DATE { get; set; }
        public string ADJ_EFF_END_DATE { get; set; }
        public Nullable<decimal> ADK_EFF_AMT { get; set; }
        public Nullable<decimal> CA_VINTAGE_MONTHS { get; set; }
        public string CA_SPEC_STATUS_FLAG { get; set; }
        public string GUTR_FLAG { get; set; }
        public Nullable<decimal> DELAY_CNT { get; set; }
        public Nullable<decimal> CCAS_UNPAID_AMT { get; set; }
        public Nullable<decimal> CCAS_USABILITY_AMT { get; set; }
        public Nullable<decimal> CCAS_UNPAID_RATE { get; set; }
        public string DATA_DATE { get; set; }
        public string REVOLVER_YN { get; set; }
        public string CA_SYSM_ADJ_REV_FLAG { get; set; }
        public string ACNO_DEDUCT_STATUS { get; set; }
        public string ACNO_DEDUCT_BANK { get; set; }
        public string ETAL_STATUS { get; set; }
        public string IDNO_TEL_RESIDENT { get; set; }
        public string IDNO_STMT_SEND_TYPE { get; set; }
        public string IDNO_IB_FLAG { get; set; }
        public string IDNO_EMAIL_ADDR { get; set; }
        public string IDNO_IND_CAT { get; set; }
        public string IDNO_POSITION { get; set; }
        public string IDNO_RESIDENT_ADDR { get; set; }
        public string IDNO_MAIL_ADDR { get; set; }
        public string IDNO_COMPANY_ADDR { get; set; }
        public Nullable<decimal> IDNO_ANNUAL_INCOME { get; set; }
        public Nullable<decimal> IDNO_IN_AMT { get; set; }
        public Nullable<decimal> IDNO_IN2_AMT { get; set; }
        public Nullable<decimal> IDNO_IN3_AMT { get; set; }
        public string IDNO_RESIDENT_ZIP { get; set; }
        public string IDNO_MAIL_ZIP { get; set; }
        public string IDNO_COMPANY_ZIP { get; set; }
    }
}
