//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RG_PARA_M_FINAL
    {
        public string RG_REASON { get; set; }
        public string EFFECT_DT { get; set; }
        public string ADJUST_DATE_S { get; set; }
        public string ADJUST_DATE_E { get; set; }
        public Nullable<decimal> APPROVE_AMT_MAX { get; set; }
        public string REMARK { get; set; }
        public string RG_REJECT { get; set; }
        public Nullable<decimal> APPROVE_SCALE_MAX { get; set; }
        public string SETUP_USERID { get; set; }
        public string SETUP_USERNAME { get; set; }
        public string SETUP_DT { get; set; }
        public string CHECK_USERID { get; set; }
        public string CHECK_USERNAME { get; set; }
        public string CHECK_DT { get; set; }
        public string SUSPEND_FLAG { get; set; }
    }
}
