//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkPower.CCLPA.DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RG_PADJUST
    {
        public string CMPN_ID { get; set; }
        public string ID { get; set; }
        public string PJNAME { get; set; }
        public Nullable<decimal> PRE_AMT { get; set; }
        public string CLOSE_DT { get; set; }
        public string IMPORT_DT { get; set; }
        public string CHI_NAME { get; set; }
        public string KIND { get; set; }
        public string SMS_CHECK { get; set; }
        public string STATUS { get; set; }
        public string USER_PROC_DTTM { get; set; }
        public string USER_ID { get; set; }
        public string DEL_PROC_DTTM { get; set; }
        public string DEL_ID { get; set; }
        public string REMARK { get; set; }
        public string STMT_CYCLE_DESC { get; set; }
        public string PAY_DEADLINE { get; set; }
        public string SAGREE_ID { get; set; }
        public string MOBIL_TEL { get; set; }
        public string REJECTREASON { get; set; }
        public string CCAS_CODE { get; set; }
        public string CCAS_STATUS { get; set; }
        public string CCAS_DT { get; set; }
    }
}
